
name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  ci:
    name: Run test
    runs-on: ubuntu-22.04
    container:
      python:3.11.1-alpine 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }} 
         
      - name: Set api environment
        run: |
          set > "com/backend/.envs/.app.dev"
      
      - name: virtual environment
        run: |
          cd com/backend/app/
          python -m  venv env
          echo "ls"
          ls
      - name: activate virtual env 
        run: |
          cd com/backend/app/
          source  env/bin/activate
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd com/backend/app/
          pip install -r requirements.txt
        
      - name: run test
        run: python ./com/backend/app/manage.py test          
        env: 
          DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
  

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: proyectopatrocinio/patrocinio
          tags: ${{ github.sha }}, ${{ github.ref_name }}-${{ github.run_id }}, latest
          registry: docker.io
          dockerfile: com/backend/app/Dockerfile
          directory: com/backend/app          
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          
  
